name: Sync Resume
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PDF
        run: |
          # Use -L to follow redirects and -o to name the final file
          curl -L "${{ secrets.OVERLEAF_PROJECT_URL }}" -o resume.pdf

      - name: Upload to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated Resume from Overleaf"
          file_pattern: 'resume.pdf'
